options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'eclipse-temurin:21'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'cd server && chmod +x gradlew && ./gradlew :App:build'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/keystroke-explorer-a0/cloud-run-source-deploy/keystroke-explorer-parser', './server']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/keystroke-explorer-a0/cloud-run-source-deploy/keystroke-explorer-parser']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'keystroke-explorer-parser', 
           '--image', 'us-central1-docker.pkg.dev/keystroke-explorer-a0/cloud-run-source-deploy/keystroke-explorer-parser',
           '--region', 'us-central1']

images:
  - 'us-central1-docker.pkg.dev/keystroke-explorer-a0/cloud-run-source-deploy/keystroke-explorer-parser'